### ISSUE TITLE
Docs: Review and update all repos based on SCM policy

### ISSUE THREAD

**Issue by roar-larsen** [equinor/dm-docs#46]
All public and internal repositories need to follow the Equinor´s SCM policy: https://developer.equinor.com/governance/scm-policy/. Highlighted policies:

- All repositories shall contain a README.md file with [fundamental information about the repo](https://github.com/equinor/it-professional-network/blob/master/onboarding/healthy_repo_guideline.md#readme-md). 
- All public repositories containing source code shall have an [open source license](https://github.com/equinor/it-professional-network/blob/master/doc/open_source/licenses.md) file and [contributing guidelines](https://github.com/equinor/it-professional-network/blob/master/onboarding/healthy_repo_guideline.md#contributing).
- All repositories shall contain a SECURITY.md file based on the [SECURITY.md template](https://github.com/equinor/it-professional-network/blob/master/doc/SECURITY-template.md).

Public:
- [x] dm-core-packages
  - [x] readme.md 
  - [x] license.md
  - [x] security.md
- [x] dm-cli
  - [x] readme.md 
  - [x] license.md
  - [x] security.md
- [x] dm-job
  - [x] readme.md 
  - [x] license.md
  - [x] security.md
- [x] create-dm-app
  - [x] readme.md 
  - [x] license.md
  - [x] security.md
- [x] dm-docs
  - [x] readme.md 
  - [x] license.md
  - [x] security.md
- [x] data-modelling-storage-service
  - [x] readme.md 
  - [x] license.md
  - [x] security.md

Old?
https://github.com/equinor/dmt-signal-demo
https://github.com/equinor/forecast-of-response
https://github.com/equinor/dm-radix
https://github.com/equinor/dm-app-analysis-platform
https://github.com/equinor/dm-app-dmt

**Comment by eoaksnes** [comment]
https://equinor.github.io/dm-docs/contributing
